/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonRounded, ButtonSize, ButtonType, ButtonVariant } from "./components/legalesign-button/legalesign-button";
export { ButtonRounded, ButtonSize, ButtonType, ButtonVariant } from "./components/legalesign-button/legalesign-button";
export namespace Components {
    interface LegalesignButton {
        "customClass"?: string;
        "disabled"?: boolean;
        "loading"?: boolean;
        "outline": boolean;
        "rounded"?: ButtonRounded;
        "size"?: ButtonSize;
        "type"?: ButtonType;
        "variant"?: ButtonVariant;
    }
    interface MyComp {
        "first": string;
        "last": string;
        "middle": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
export interface LegalesignButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLegalesignButtonElement;
}
declare global {
    interface HTMLLegalesignButtonElementEventMap {
        "onClick": any;
    }
    interface HTMLLegalesignButtonElement extends Components.LegalesignButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLegalesignButtonElementEventMap>(type: K, listener: (this: HTMLLegalesignButtonElement, ev: LegalesignButtonCustomEvent<HTMLLegalesignButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLegalesignButtonElementEventMap>(type: K, listener: (this: HTMLLegalesignButtonElement, ev: LegalesignButtonCustomEvent<HTMLLegalesignButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLegalesignButtonElement: {
        prototype: HTMLLegalesignButtonElement;
        new (): HTMLLegalesignButtonElement;
    };
    interface HTMLMyCompElement extends Components.MyComp, HTMLStencilElement {
    }
    var HTMLMyCompElement: {
        prototype: HTMLMyCompElement;
        new (): HTMLMyCompElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "legalesign-button": HTMLLegalesignButtonElement;
        "my-comp": HTMLMyCompElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface LegalesignButton {
        "customClass"?: string;
        "disabled"?: boolean;
        "loading"?: boolean;
        "onOnClick"?: (event: LegalesignButtonCustomEvent<any>) => void;
        "outline"?: boolean;
        "rounded"?: ButtonRounded;
        "size"?: ButtonSize;
        "type"?: ButtonType;
        "variant"?: ButtonVariant;
    }
    interface MyComp {
        "first"?: string;
        "last"?: string;
        "middle"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "legalesign-button": LegalesignButton;
        "my-comp": MyComp;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "legalesign-button": LocalJSX.LegalesignButton & JSXBase.HTMLAttributes<HTMLLegalesignButtonElement>;
            "my-comp": LocalJSX.MyComp & JSXBase.HTMLAttributes<HTMLMyCompElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
